--insert into user(email, nick_name, name,pass,role) values('admin','관리자','관리자','$2a$10$rvNYah11hiVaf53P1nwxKOHqPgxJOkfVMIyqGAnHmGKY8ZtOqZ5h2','ROLE_ADMIN');
--insert into user(email, nick_name, name,pass) values('various@naver.com','홍길동의 후예','홍길동','$2a$10$r0ealayqf/Zq1xOTmQZccuxz54UN7kvk7rP0WKdQCSTR4KS6vXWgi');
